server:
  port: 8080


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gate-way-service

  cloud:
    gateway:
      routes:
        - id: addressService
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/address/**
        - id: customerService
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
        - id: webUIService
          uri: lb://WEB-UI-SERVICE
          predicates:
            - Path=/webui/**,/bootstrap/**